//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEspackeuro {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idiomas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebEspackeuro.Idiomas", typeof(Idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGOSTO DE 2.004.
        /// </summary>
        public static string Agosto2004 {
            get {
                return ResourceManager.GetString("Agosto2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alemania.
        /// </summary>
        public static string Alemania {
            get {
                return ResourceManager.GetString("Alemania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacén Aduanero.
        /// </summary>
        public static string AlmacenAduanero {
            get {
                return ResourceManager.GetString("AlmacenAduanero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenaje.
        /// </summary>
        public static string Almacenaje {
            get {
                return ResourceManager.GetString("Almacenaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de logística integral de almacenaje:.
        /// </summary>
        public static string AlmacenL1 {
            get {
                return ResourceManager.GetString("AlmacenL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepción de los productos.
        /// </summary>
        public static string AlmacenL2 {
            get {
                return ResourceManager.GetString("AlmacenL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecución de un control de calidad inmediato.
        /// </summary>
        public static string AlmacenL3 {
            get {
                return ResourceManager.GetString("AlmacenL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control e inventario de todos los productos almacenados.
        /// </summary>
        public static string AlmacenL4 {
            get {
                return ResourceManager.GetString("AlmacenL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenamiento según tipos de producto, diferentes caducidades, rotación y número de referencias.
        /// </summary>
        public static string AlmacenL5 {
            get {
                return ResourceManager.GetString("AlmacenL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparación y expedición de los pedidos.
        /// </summary>
        public static string AlmacenL6 {
            get {
                return ResourceManager.GetString("AlmacenL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de entradas y salidas: sistemas fifo, lifo, nifo,....
        /// </summary>
        public static string AlmacenL7 {
            get {
                return ResourceManager.GetString("AlmacenL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemas de radiofrecuencia.
        /// </summary>
        public static string AlmacenL8 {
            get {
                return ResourceManager.GetString("AlmacenL8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string Asunto {
            get {
                return ResourceManager.GetString("Asunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridgend.
        /// </summary>
        public static string Bridgend {
            get {
                return ResourceManager.GetString("Bridgend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Bromwich.
        /// </summary>
        public static string CastleBromwich {
            get {
                return ResourceManager.GetString("CastleBromwich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de trasvase a contenedores específicos:.
        /// </summary>
        public static string CenConL1 {
            get {
                return ResourceManager.GetString("CenConL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento del perfecto estado de los contenedores..
        /// </summary>
        public static string CenConL2 {
            get {
                return ResourceManager.GetString("CenConL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conocer la exacta ubicación y estado del contenedor en todo momento..
        /// </summary>
        public static string CenConL3 {
            get {
                return ResourceManager.GetString("CenConL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticiparse y evitar posibles situaciones de desabastecimiento..
        /// </summary>
        public static string CenConL4 {
            get {
                return ResourceManager.GetString("CenConL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificar áreas donde no se efectue una rotación adecuada..
        /// </summary>
        public static string CenConL5 {
            get {
                return ResourceManager.GetString("CenConL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponer de una trazabilidad que permita depurar las responsabilidades en caso de daños o uso indebido..
        /// </summary>
        public static string CenConL6 {
            get {
                return ResourceManager.GetString("CenConL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponer de datos necesarios para optimizar el parque de contenedores, así como programar de la forma más eficaz el mantenimiento de los mismos y su eventual reposición..
        /// </summary>
        public static string CenConL7 {
            get {
                return ResourceManager.GetString("CenConL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro Consolidador de Contenedores.
        /// </summary>
        public static string Centroconsolidadorcontenedores {
            get {
                return ResourceManager.GetString("Centroconsolidadorcontenedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados.
        /// </summary>
        public static string CERTIFICADOS {
            get {
                return ResourceManager.GetString("CERTIFICADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados y Premios.
        /// </summary>
        public static string CertificadosPremios {
            get {
                return ResourceManager.GetString("CertificadosPremios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonia.
        /// </summary>
        public static string Colonia {
            get {
                return ResourceManager.GetString("Colonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craiova.
        /// </summary>
        public static string Craiova {
            get {
                return ResourceManager.GetString("Craiova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagenham.
        /// </summary>
        public static string Dagenham {
            get {
                return ResourceManager.GetString("Dagenham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de trasvase a contenedores específicos:.
        /// </summary>
        public static string DistribucionL1 {
            get {
                return ResourceManager.GetString("DistribucionL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasvase del material de embalaje deshechable a embalaje duradero..
        /// </summary>
        public static string DistribucionL2 {
            get {
                return ResourceManager.GetString("DistribucionL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasvasar el material que viene en contenedores no aptos para la cadena de producción a contenedores KLT..
        /// </summary>
        public static string DistribucionL3 {
            get {
                return ResourceManager.GetString("DistribucionL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasvasar el material que llega empaquetado para la optimización del transporte a contenedores y cantidades determinadas por el cliente..
        /// </summary>
        public static string DistribucionL4 {
            get {
                return ResourceManager.GetString("DistribucionL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobertura Internacional de.
        /// </summary>
        public static string DistribucionL5 {
            get {
                return ResourceManager.GetString("DistribucionL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribución Nacional e Internacional.
        /// </summary>
        public static string Distribucnacionalinter {
            get {
                return ResourceManager.GetString("Distribucnacionalinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logística de Comercio Electrónico.
        /// </summary>
        public static string Ecommerce {
            get {
                return ResourceManager.GetString("Ecommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepción de Mercancías en Contenedores Marítimos.
        /// </summary>
        public static string EcommerceL1 {
            get {
                return ResourceManager.GetString("EcommerceL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación con código de barras RF en almacén.
        /// </summary>
        public static string EcommerceL2 {
            get {
                return ResourceManager.GetString("EcommerceL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking según demandas diarias en vivo.
        /// </summary>
        public static string EcommerceL3 {
            get {
                return ResourceManager.GetString("EcommerceL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integración con el ERP del cliente a través de la interfaz de sistemas.
        /// </summary>
        public static string EcommerceL4 {
            get {
                return ResourceManager.GetString("EcommerceL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectividad EDI.
        /// </summary>
        public static string EcommerceL5 {
            get {
                return ResourceManager.GetString("EcommerceL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega en furgoneta – último kilómetro.
        /// </summary>
        public static string EcommerceL6 {
            get {
                return ResourceManager.GetString("EcommerceL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de logística inversa.
        /// </summary>
        public static string EcommerceL7 {
            get {
                return ResourceManager.GetString("EcommerceL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email de contacto.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas del Grupo Espack.
        /// </summary>
        public static string Empresas {
            get {
                return ResourceManager.GetString("Empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVÍENOS SUS PREGUNTAS.
        /// </summary>
        public static string EnviePreguntas {
            get {
                return ResourceManager.GetString("EnviePreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitra.
        /// </summary>
        public static string Eslovaquia {
            get {
                return ResourceManager.GetString("Eslovaquia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FABRICA FORD.
        /// </summary>
        public static string FABRICAFORD {
            get {
                return ResourceManager.GetString("FABRICAFORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA DE CREACIÓN:.
        /// </summary>
        public static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GALARDONES Y CERTIFICACIONES:.
        /// </summary>
        public static string GALARDONES {
            get {
                return ResourceManager.GetString("GALARDONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graz.
        /// </summary>
        public static string Graz {
            get {
                return ResourceManager.GetString("Graz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000 m2 de instalaciones, en el interior del centro de suministro de Magna Steyr.
        /// </summary>
        public static string GrazL1 {
            get {
                return ResourceManager.GetString("GrazL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area de consolidación, suministro a línea  y distribución dentro de la planta Magna Steyr.
        /// </summary>
        public static string GrazL2 {
            get {
                return ResourceManager.GetString("GrazL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software propio a medida del cliente y sistemas de conexión on-line con el cliente.
        /// </summary>
        public static string GrazL3 {
            get {
                return ResourceManager.GetString("GrazL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última tecnología en maquinaria y sistemas.
        /// </summary>
        public static string GrazL4 {
            get {
                return ResourceManager.GetString("GrazL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halewood.
        /// </summary>
        public static string Halewood {
            get {
                return ResourceManager.GetString("Halewood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software propio a medida del cliente y sistemas de conexión on-line con el cliente.
        /// </summary>
        public static string HalewoodL1 {
            get {
                return ResourceManager.GetString("HalewoodL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suministro a línea en Jaguar Land Rover.
        /// </summary>
        public static string HalewoodL2 {
            get {
                return ResourceManager.GetString("HalewoodL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última tecnología en maquinaria y sistemas.
        /// </summary>
        public static string HalewoodL3 {
            get {
                return ResourceManager.GetString("HalewoodL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFRAESTRUCTURA:.
        /// </summary>
        public static string INFRAESTRUCTURA {
            get {
                return ResourceManager.GetString("INFRAESTRUCTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNIO DE 2.016.
        /// </summary>
        public static string Junio2016 {
            get {
                return ResourceManager.GetString("Junio2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logística de Empaquetado.
        /// </summary>
        public static string LogEmpaquetado {
            get {
                return ResourceManager.GetString("LogEmpaquetado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de logística integral de empaquetado:.
        /// </summary>
        public static string LogEmpaquetadoL1 {
            get {
                return ResourceManager.GetString("LogEmpaquetadoL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material de embalaje según especificaciones del cliente.
        /// </summary>
        public static string LogEmpaquetadoL2 {
            get {
                return ResourceManager.GetString("LogEmpaquetadoL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diversidad de embalajes por tipo de producto, por referencias y por cliente.
        /// </summary>
        public static string LogEmpaquetadoL3 {
            get {
                return ResourceManager.GetString("LogEmpaquetadoL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empaquetado manual.
        /// </summary>
        public static string LogEmpaquetadoL4 {
            get {
                return ResourceManager.GetString("LogEmpaquetadoL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empaquetado automático.
        /// </summary>
        public static string LogEmpaquetadoL5 {
            get {
                return ResourceManager.GetString("LogEmpaquetadoL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retractilado.
        /// </summary>
        public static string LogEmpaquetadoL6 {
            get {
                return ResourceManager.GetString("LogEmpaquetadoL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blisters.
        /// </summary>
        public static string LogEmpaquetadoL7 {
            get {
                return ResourceManager.GetString("LogEmpaquetadoL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logística de Identificación.
        /// </summary>
        public static string LogIdentificación {
            get {
                return ResourceManager.GetString("LogIdentificación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta adhesiva de papel..
        /// </summary>
        public static string LogIdentificacionL1 {
            get {
                return ResourceManager.GetString("LogIdentificacionL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta adhesiva de polietileno..
        /// </summary>
        public static string LogIdentificacionL2 {
            get {
                return ResourceManager.GetString("LogIdentificacionL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta adhesiva máxima seguridad: Papel moneda..
        /// </summary>
        public static string LogIdentificacionL3 {
            get {
                return ResourceManager.GetString("LogIdentificacionL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inyección de tinta sobre el embalaje..
        /// </summary>
        public static string LogIdentificacionL4 {
            get {
                return ResourceManager.GetString("LogIdentificacionL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación impresa por código de barras..
        /// </summary>
        public static string LogIdentificacionL5 {
            get {
                return ResourceManager.GetString("LogIdentificacionL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logística integral de almacén.
        /// </summary>
        public static string LogIntegralAlmacen {
            get {
                return ResourceManager.GetString("LogIntegralAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logística de Selección.
        /// </summary>
        public static string LogSeleccion {
            get {
                return ResourceManager.GetString("LogSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de logística integral de selección que consiste en seleccionar diferentes productos que serán enviados a una misma dirección, previa manipulación, si así lo requiere el cliente....
        /// </summary>
        public static string LogSeleccionL1 {
            get {
                return ResourceManager.GetString("LogSeleccionL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logística Inversa.
        /// </summary>
        public static string LogSeleccionL2 {
            get {
                return ResourceManager.GetString("LogSeleccionL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio complementario al servicio de selección o picking. Gestionamos las devoluciones de material que los concesionarios de nuestro cliente retornan por problemas de calidad, daños, errores de pedido,....
        /// </summary>
        public static string LogSeleccionL3 {
            get {
                return ResourceManager.GetString("LogSeleccionL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estas piezas se recepcionan, se clasifican por causa de devolución y según instrucciones del cliente, se procede a la siguiente fase o servicio..
        /// </summary>
        public static string LogSeleccionL4 {
            get {
                return ResourceManager.GetString("LogSeleccionL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUGAR PRINCIPAL DE TRABAJO:.
        /// </summary>
        public static string LUGARPRINCIPALTRABAJO {
            get {
                return ResourceManager.GetString("LUGARPRINCIPALTRABAJO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUGAR SECUNDARIO DE TRABAJO:.
        /// </summary>
        public static string LUGARSECUNDARIOTRABAJO {
            get {
                return ResourceManager.GetString("LUGARSECUNDARIOTRABAJO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m2 de instalaciones.
        /// </summary>
        public static string M2Instalaciones {
            get {
                return ResourceManager.GetString("M2Instalaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madrid.
        /// </summary>
        public static string Madrid {
            get {
                return ResourceManager.GetString("Madrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPLANTACIÓN DE SISTEMAS DE CALIDAD..
        /// </summary>
        public static string MadridL1 {
            get {
                return ResourceManager.GetString("MadridL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESARROLLO E IMPLANTACIÓN DE SOFTWARE A MEDIDA DE LAS NECESIDADES DEL CLIENTE..
        /// </summary>
        public static string MadridL2 {
            get {
                return ResourceManager.GetString("MadridL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPLANTACIÓN DE SISTEMAS QUE GARANTICEN LA PREVENCIÓN DE  RIESGOS LABORALES..
        /// </summary>
        public static string MadridL3 {
            get {
                return ResourceManager.GetString("MadridL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÚSQUEDA DE SUBVENCIONES..
        /// </summary>
        public static string MadridL4 {
            get {
                return ResourceManager.GetString("MadridL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGALOS DE EMPRESA..
        /// </summary>
        public static string MadridL5 {
            get {
                return ResourceManager.GetString("MadridL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICIO INTEGRAL DE IDIOMAS..
        /// </summary>
        public static string MadridL6 {
            get {
                return ResourceManager.GetString("MadridL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASESORÍA EN MATERIAL FISCAL, LABORAL Y CONTABLE..
        /// </summary>
        public static string MadridL7 {
            get {
                return ResourceManager.GetString("MadridL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARRENDAMIENTO DE NAVES INDUSTRIALES Y VIVIENDAS..
        /// </summary>
        public static string MadridL8 {
            get {
                return ResourceManager.GetString("MadridL8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulados.
        /// </summary>
        public static string Manipulados {
            get {
                return ResourceManager.GetString("Manipulados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARZO DE 1.971.
        /// </summary>
        public static string Marzo1971 {
            get {
                return ResourceManager.GetString("Marzo1971", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARZO DE 2.017.
        /// </summary>
        public static string Marzo2017 {
            get {
                return ResourceManager.GetString("Marzo2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARZO DE 2.020.
        /// </summary>
        public static string Marzo2020 {
            get {
                return ResourceManager.GetString("Marzo2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYO DE 1.978.
        /// </summary>
        public static string Mayo1978 {
            get {
                return ResourceManager.GetString("Mayo1978", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYO DE 1.988.
        /// </summary>
        public static string Mayo1988 {
            get {
                return ResourceManager.GetString("Mayo1988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYO DE 2.010.
        /// </summary>
        public static string Mayo2010 {
            get {
                return ResourceManager.GetString("Mayo2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYO DE 2.012.
        /// </summary>
        public static string Mayo2012 {
            get {
                return ResourceManager.GetString("Mayo2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAYO DE 2.014.
        /// </summary>
        public static string Mayo2014 {
            get {
                return ResourceManager.GetString("Mayo2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios.
        /// </summary>
        public static string Medios {
            get {
                return ResourceManager.GetString("Medios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios de los que dispone Espack Eurologística:.
        /// </summary>
        public static string MediosL1 {
            get {
                return ResourceManager.GetString("MediosL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabina de aceitado.
        /// </summary>
        public static string MediosL10 {
            get {
                return ResourceManager.GetString("MediosL10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabina de imprimación.
        /// </summary>
        public static string MediosL11 {
            get {
                return ResourceManager.GetString("MediosL11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carretillas bilaterales, trilaterales, rectráctiles,….
        /// </summary>
        public static string MediosL12 {
            get {
                return ResourceManager.GetString("MediosL12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software propio a medida de cada cliente y servicio: código de barras, radiofrecuencia,….
        /// </summary>
        public static string MediosL13 {
            get {
                return ResourceManager.GetString("MediosL13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemas de conexión con el cliente: EDI, Catalyst, Pluma, Abtail, Marc, Comet,….
        /// </summary>
        public static string MediosL14 {
            get {
                return ResourceManager.GetString("MediosL14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal debidamente formado en cada área.
        /// </summary>
        public static string MediosL15 {
            get {
                return ResourceManager.GetString("MediosL15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingeniería, diseño, informática, producción,….
        /// </summary>
        public static string MediosL16 {
            get {
                return ResourceManager.GetString("MediosL16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.000 m2 de instalaciones.
        /// </summary>
        public static string MediosL2 {
            get {
                return ResourceManager.GetString("MediosL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte nacional e internacional para todas sus mercancías.
        /// </summary>
        public static string MediosL3 {
            get {
                return ResourceManager.GetString("MediosL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estanterías de aprovisionamiento según necesidades del producto.
        /// </summary>
        public static string MediosL4 {
            get {
                return ResourceManager.GetString("MediosL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muelles de carga y descarga multidisciplinares.
        /// </summary>
        public static string MediosL5 {
            get {
                return ResourceManager.GetString("MediosL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de temperatura controlada.
        /// </summary>
        public static string MediosL6 {
            get {
                return ResourceManager.GetString("MediosL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas de humedad controlada.
        /// </summary>
        public static string MediosL7 {
            get {
                return ResourceManager.GetString("MediosL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máxima ergonomía: Implantación de lineales adecuadas a la geometría del local:.
        /// </summary>
        public static string MediosL8 {
            get {
                return ResourceManager.GetString("MediosL8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabina de pintura.
        /// </summary>
        public static string MediosL9 {
            get {
                return ResourceManager.GetString("MediosL9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de logística integral de montajes, submontajes y preparación de conjuntos basado en la recepción de distintos componentes de proveedores diferentes, que tras un adecuado proceso de montaje dan como resultado un semiproducto que precisará un posterior proceso de montaje o directamente dará como resultado un producto final..
        /// </summary>
        public static string MonPreConL1 {
            get {
                return ResourceManager.GetString("MonPreConL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejemplos de premontajes:.
        /// </summary>
        public static string MonPreConL2 {
            get {
                return ResourceManager.GetString("MonPreConL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubo de refrigeración.
        /// </summary>
        public static string MonPreConL3 {
            get {
                return ResourceManager.GetString("MonPreConL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedal de freno.
        /// </summary>
        public static string MonPreConL4 {
            get {
                return ResourceManager.GetString("MonPreConL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emburletado de cristales.
        /// </summary>
        public static string MonPreConL5 {
            get {
                return ResourceManager.GetString("MonPreConL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amortiguador trasero.
        /// </summary>
        public static string MonPreConL6 {
            get {
                return ResourceManager.GetString("MonPreConL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barra estabilizadora.
        /// </summary>
        public static string MonPreConL7 {
            get {
                return ResourceManager.GetString("MonPreConL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montajes y Preparación de Conjuntos.
        /// </summary>
        public static string Montajespreparaconjuntos {
            get {
                return ResourceManager.GetString("Montajespreparaconjuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFICINAS CENTRALES:.
        /// </summary>
        public static string OficinasCentrales {
            get {
                return ResourceManager.GetString("OficinasCentrales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprende una serie de compañías logísticas dedicadas a todas aquellas actividades que, en función del volumen o complejidad de gestión, son susceptibles de ser realizadas de forma independiente del proceso normal de fabricación, permitiendo a las empresas concentrarse en su actividad principal y de esta forma... INCREMENTAR SU COMPETITIVIDAD.
        /// </summary>
        public static string Pag_Que_es_Espack {
            get {
                return ResourceManager.GetString("Pag_Que_es_Espack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espack, Servicios Logísticos Integrales, proporciona los siguientes servicios logísticos:.
        /// </summary>
        public static string Pag_ServiciosLog {
            get {
                return ResourceManager.GetString("Pag_ServiciosLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantas.
        /// </summary>
        public static string Plantas {
            get {
                return ResourceManager.GetString("Plantas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política Integrada de Gestión.
        /// </summary>
        public static string Politica {
            get {
                return ResourceManager.GetString("Politica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premios.
        /// </summary>
        public static string PREMIOS {
            get {
                return ResourceManager.GetString("PREMIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesos Logísticos Especiales.
        /// </summary>
        public static string Proclogespeciales {
            get {
                return ResourceManager.GetString("Proclogespeciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estamos abiertos a cualquier sistema o proceso que precise el cliente en su material..
        /// </summary>
        public static string ProLogEspL1 {
            get {
                return ResourceManager.GetString("ProLogEspL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunos ejemplos:.
        /// </summary>
        public static string ProLogEspL2 {
            get {
                return ResourceManager.GetString("ProLogEspL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CKD: Es un programa de envío de componentes de automoción de determinados modelos de vehículos, desde la planta de fabricación de dichos automóviles a otra planta ubicada en un país distinto, donde se procederá al ensamblaje de los mismos..
        /// </summary>
        public static string ProLogEspL3 {
            get {
                return ResourceManager.GetString("ProLogEspL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD: Es un programa que consiste en desmontar algunos de los componentes del vehículo y en dotarles de la máxima protección para su envío junto al vehículo del que han sido desmontados, desde la planta de fabricación de dichos automóviles a otra planta ubicada en un país distinto, donde se procederá al ensamblaje de los mismos..
        /// </summary>
        public static string ProLogEspL4 {
            get {
                return ResourceManager.GetString("ProLogEspL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpieza, imprimación, emburletado y suministro de cristales a la cadena de producción..
        /// </summary>
        public static string ProLogEspL5 {
            get {
                return ResourceManager.GetString("ProLogEspL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellado de chapa..
        /// </summary>
        public static string ProLogEspL6 {
            get {
                return ResourceManager.GetString("ProLogEspL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Punto {
            get {
                return ResourceManager.GetString("Punto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué es Espack Eurologística?.
        /// </summary>
        public static string Que_es_Espack {
            get {
                return ResourceManager.GetString("Que_es_Espack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisión, Inspección y Recuperación.
        /// </summary>
        public static string RevInspRecu {
            get {
                return ResourceManager.GetString("RevInspRecu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de logística integral de revisión, inspección y recuperación:.
        /// </summary>
        public static string RevInsRecuL1 {
            get {
                return ResourceManager.GetString("RevInsRecuL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por indicaciones del cliente, ó por detección nuestra, podemos revisar los componentes de cualquier conjunto antes de su montaje, o de material terminado antes de expedirlo al cliente final, ante la posibilidad de que pueda tener algún tipo de defecto o desviación producida durante su fabricación..
        /// </summary>
        public static string RevInsRecuL2 {
            get {
                return ResourceManager.GetString("RevInsRecuL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El material revisado o seleccionado puede ser recuperado con operaciones de manipulado con herramientas técnicas específicas para transformar el material en APTO..
        /// </summary>
        public static string RevInsRecuL3 {
            get {
                return ResourceManager.GetString("RevInsRecuL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Soy un Robot.
        /// </summary>
        public static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saarlouis.
        /// </summary>
        public static string Saarlouis {
            get {
                return ResourceManager.GetString("Saarlouis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione acceso a nuestra web.
        /// </summary>
        public static string SeleccionWeb {
            get {
                return ResourceManager.GetString("SeleccionWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPTIEMBRE DE 2.013.
        /// </summary>
        public static string Septiembre13 {
            get {
                return ResourceManager.GetString("Septiembre13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICIOS:.
        /// </summary>
        public static string SERVICIOS {
            get {
                return ResourceManager.GetString("SERVICIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios Logísticos.
        /// </summary>
        public static string ServiciosLog {
            get {
                return ResourceManager.GetString("ServiciosLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollamos nuestro propio software a medida. Esto significa máxima flexibilidad en el proceso de información y la capacidad de realizar mejoras y añadir nuevos servicios..
        /// </summary>
        public static string SoftwareL1 {
            get {
                return ResourceManager.GetString("SoftwareL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debido a nuestra capacidad de personalización, podemos crear interfaces de importación/exportación que vinculen las aplicaciones de nuestros clientes con las nuestras para garantizar una óptima respuesta y flujo de información..
        /// </summary>
        public static string SoftwareL2 {
            get {
                return ResourceManager.GetString("SoftwareL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestro software EWS (Espack Warehousing  System) nos permite obtener información detallada de las llegadas, stocks, expediciones, control de FIFO, discrepancias, etc..
        /// </summary>
        public static string SoftwareL3 {
            get {
                return ResourceManager.GetString("SoftwareL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una de nuestras empresas es responsable de cualquier tema relacionado con IT: desarrollo y mantenimiento de software, instalación y mantenimiento de hardware, I+D para mejoras o nuevos proyectos, etc..
        /// </summary>
        public static string SoftwareL4 {
            get {
                return ResourceManager.GetString("SoftwareL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suministro.
        /// </summary>
        public static string Suministro {
            get {
                return ResourceManager.GetString("Suministro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasvase a Contenedores Especificos.
        /// </summary>
        public static string Trasvaseacontenedoresespec {
            get {
                return ResourceManager.GetString("Trasvaseacontenedoresespec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ofrecemos las siguientes soluciones de trasvase a contenedores específicos:.
        /// </summary>
        public static string TrasvaseL1 {
            get {
                return ResourceManager.GetString("TrasvaseL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasvase del material de embalaje deshechable a embalaje duradero..
        /// </summary>
        public static string TrasvaseL2 {
            get {
                return ResourceManager.GetString("TrasvaseL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasvasar el material que viene en contenedores no aptos para la cadena de producción a contenedores KLT..
        /// </summary>
        public static string TrasvaseL3 {
            get {
                return ResourceManager.GetString("TrasvaseL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasvasar el material que llega empaquetado para la optimización del transporte a contenedores y cantidades determinadas por el cliente..
        /// </summary>
        public static string TrasvaseL4 {
            get {
                return ResourceManager.GetString("TrasvaseL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valencia.
        /// </summary>
        public static string Valencia {
            get {
                return ResourceManager.GetString("Valencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software propio a medida del cliente y sistemas de conexión on-line con el cliente.
        /// </summary>
        public static string ValenciaL1 {
            get {
                return ResourceManager.GetString("ValenciaL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última tecnología en maquinaria y sistemas.
        /// </summary>
        public static string ValenciaL2 {
            get {
                return ResourceManager.GetString("ValenciaL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premio a la Excelencia Empresarial.
        /// </summary>
        public static string ValenciaL3 {
            get {
                return ResourceManager.GetString("ValenciaL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera Empresa de Servicios en Europa que alcanza el Q-1.
        /// </summary>
        public static string ValenciaL4 {
            get {
                return ResourceManager.GetString("ValenciaL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto de Sustitución del Sistema de Iluminación en el año 2015. Programa de ahorro y eficiencia energética en la Industria (Programa financiado por el Instituto Valenciano de Competitividad Empresarial- IVACE y los Fondos FEDER)..
        /// </summary>
        public static string ValenciaL5 {
            get {
                return ResourceManager.GetString("ValenciaL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventajas Ofrecidas.
        /// </summary>
        public static string Ventajas {
            get {
                return ResourceManager.GetString("Ventajas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECONOMÍA.
        /// </summary>
        public static string VentajasL1 {
            get {
                return ResourceManager.GetString("VentajasL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibilidad para atender operaciones especiales: puntas y valles..
        /// </summary>
        public static string VentajasL10 {
            get {
                return ResourceManager.GetString("VentajasL10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información puntual del estado del producto: control informático de la trazabilidad..
        /// </summary>
        public static string VentajasL11 {
            get {
                return ResourceManager.GetString("VentajasL11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducción de riesgos operativos y financieros..
        /// </summary>
        public static string VentajasL12 {
            get {
                return ResourceManager.GetString("VentajasL12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARANTÍA.
        /// </summary>
        public static string VentajasL13 {
            get {
                return ResourceManager.GetString("VentajasL13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiencia y profesionalidad acumuladas desde 1978..
        /// </summary>
        public static string VentajasL14 {
            get {
                return ResourceManager.GetString("VentajasL14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconocimientos de grandes compañías..
        /// </summary>
        public static string VentajasL15 {
            get {
                return ResourceManager.GetString("VentajasL15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas pioneras en obtener las principales certificaciones de calidad..
        /// </summary>
        public static string VentajasL16 {
            get {
                return ResourceManager.GetString("VentajasL16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga de tiempos de personal que absorben actividades accesorias a la actividad principal..
        /// </summary>
        public static string VentajasL2 {
            get {
                return ResourceManager.GetString("VentajasL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducción de inventario: suministro según necesidades del cliente..
        /// </summary>
        public static string VentajasL3 {
            get {
                return ResourceManager.GetString("VentajasL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimización de medios inherentes a la actividad principal..
        /// </summary>
        public static string VentajasL4 {
            get {
                return ResourceManager.GetString("VentajasL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahorro en inversiones en tecnología e investigación sobre área no objeto del negocio..
        /// </summary>
        public static string VentajasL5 {
            get {
                return ResourceManager.GetString("VentajasL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación de barreras de expansión..
        /// </summary>
        public static string VentajasL6 {
            get {
                return ResourceManager.GetString("VentajasL6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGURIDAD.
        /// </summary>
        public static string VentajasL7 {
            get {
                return ResourceManager.GetString("VentajasL7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conocimiento y participación en la logística de grandes compañías..
        /// </summary>
        public static string VentajasL8 {
            get {
                return ResourceManager.GetString("VentajasL8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducción de plazos productivos..
        /// </summary>
        public static string VentajasL9 {
            get {
                return ResourceManager.GetString("VentajasL9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 min. de lectura.
        /// </summary>
        public static string Web1Titulo {
            get {
                return ResourceManager.GetString("Web1Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutos de lectura.
        /// </summary>
        public static string Web2Titulo {
            get {
                return ResourceManager.GetString("Web2Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolverhampton.
        /// </summary>
        public static string Wolverhampton {
            get {
                return ResourceManager.GetString("Wolverhampton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacenamiento, reembalaje e inspecciones de control de calidad.
        /// </summary>
        public static string WolverhamptonL1 {
            get {
                return ResourceManager.GetString("WolverhamptonL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaragoza.
        /// </summary>
        public static string Zaragoza {
            get {
                return ResourceManager.GetString("Zaragoza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.000 m2 de espacio abierto.
        /// </summary>
        public static string ZaragozaL1 {
            get {
                return ResourceManager.GetString("ZaragozaL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software propio a medida del cliente y sistemas de conexión on-line con el cliente.
        /// </summary>
        public static string ZaragozaL2 {
            get {
                return ResourceManager.GetString("ZaragozaL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última tecnología en maquinaria y sistemas.
        /// </summary>
        public static string ZaragozaL3 {
            get {
                return ResourceManager.GetString("ZaragozaL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSP (Quality Service and Price).
        /// </summary>
        public static string ZaragozaL4 {
            get {
                return ResourceManager.GetString("ZaragozaL4", resourceCulture);
            }
        }
    }
}
