#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RadioSequencing.Resource", IsApplication=true)]

namespace RadioSequencing
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int accent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int accent_pressed = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ic_launcher_background = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int primary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int primary_pressed = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ripple = 2130771973;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_margin = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030002
			public const int at = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int au = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int br = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int ca = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ch = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int cl = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int cn = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int cz = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int de = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int divider = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int dk = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int ee = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int fi = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int fr = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int gr = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int hr = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int hu = 2130903058;
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7F030016
			public const int icon2 = 2130903062;
			
			// aapt resource value: 0x7F030013
			public const int ic_action_content_new = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int ic_add_white_24dp = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int ic_launcher = 2130903061;
			
			// aapt resource value: 0x7F030017
			public const int ie = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int @in = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int @is = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int it = 2130903066;
			
			// aapt resource value: 0x7F030001
			public const int Logo_Espack_Sistemas_vertical = 2130903041;
			
			// aapt resource value: 0x7F03001B
			public const int lt = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int lv = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int nl = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int no = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int nz = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int roundButton = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int se = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int ua = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int us = 2130903075;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int Anio1 = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Anio2 = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Anio3 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Anio4 = 2130968579;
			
			// aapt resource value: 0x7F040034
			public const int batch = 2130968628;
			
			// aapt resource value: 0x7F040004
			public const int Bronce3 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Bronce4 = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int BronceTotal = 2130968582;
			
			// aapt resource value: 0x7F040035
			public const int c00 = 2130968629;
			
			// aapt resource value: 0x7F040036
			public const int c01 = 2130968630;
			
			// aapt resource value: 0x7F040037
			public const int c02 = 2130968631;
			
			// aapt resource value: 0x7F040038
			public const int c03 = 2130968632;
			
			// aapt resource value: 0x7F040039
			public const int c10 = 2130968633;
			
			// aapt resource value: 0x7F04003A
			public const int c100 = 2130968634;
			
			// aapt resource value: 0x7F04003B
			public const int c101 = 2130968635;
			
			// aapt resource value: 0x7F04003C
			public const int c102 = 2130968636;
			
			// aapt resource value: 0x7F04003D
			public const int c103 = 2130968637;
			
			// aapt resource value: 0x7F04003E
			public const int c11 = 2130968638;
			
			// aapt resource value: 0x7F04003F
			public const int c110 = 2130968639;
			
			// aapt resource value: 0x7F040040
			public const int c111 = 2130968640;
			
			// aapt resource value: 0x7F040041
			public const int c112 = 2130968641;
			
			// aapt resource value: 0x7F040042
			public const int c113 = 2130968642;
			
			// aapt resource value: 0x7F040043
			public const int c12 = 2130968643;
			
			// aapt resource value: 0x7F040044
			public const int c13 = 2130968644;
			
			// aapt resource value: 0x7F040045
			public const int c20 = 2130968645;
			
			// aapt resource value: 0x7F040046
			public const int c21 = 2130968646;
			
			// aapt resource value: 0x7F040047
			public const int c22 = 2130968647;
			
			// aapt resource value: 0x7F040048
			public const int c23 = 2130968648;
			
			// aapt resource value: 0x7F040049
			public const int c30 = 2130968649;
			
			// aapt resource value: 0x7F04004A
			public const int c31 = 2130968650;
			
			// aapt resource value: 0x7F04004B
			public const int c32 = 2130968651;
			
			// aapt resource value: 0x7F04004C
			public const int c33 = 2130968652;
			
			// aapt resource value: 0x7F04004D
			public const int c40 = 2130968653;
			
			// aapt resource value: 0x7F04004E
			public const int c41 = 2130968654;
			
			// aapt resource value: 0x7F04004F
			public const int c42 = 2130968655;
			
			// aapt resource value: 0x7F040050
			public const int c43 = 2130968656;
			
			// aapt resource value: 0x7F040051
			public const int c50 = 2130968657;
			
			// aapt resource value: 0x7F040052
			public const int c51 = 2130968658;
			
			// aapt resource value: 0x7F040053
			public const int c52 = 2130968659;
			
			// aapt resource value: 0x7F040054
			public const int c53 = 2130968660;
			
			// aapt resource value: 0x7F040055
			public const int c60 = 2130968661;
			
			// aapt resource value: 0x7F040056
			public const int c61 = 2130968662;
			
			// aapt resource value: 0x7F040057
			public const int c62 = 2130968663;
			
			// aapt resource value: 0x7F040058
			public const int c63 = 2130968664;
			
			// aapt resource value: 0x7F040059
			public const int c70 = 2130968665;
			
			// aapt resource value: 0x7F04005A
			public const int c71 = 2130968666;
			
			// aapt resource value: 0x7F04005B
			public const int c72 = 2130968667;
			
			// aapt resource value: 0x7F04005C
			public const int c73 = 2130968668;
			
			// aapt resource value: 0x7F04005D
			public const int c80 = 2130968669;
			
			// aapt resource value: 0x7F04005E
			public const int c81 = 2130968670;
			
			// aapt resource value: 0x7F04005F
			public const int c82 = 2130968671;
			
			// aapt resource value: 0x7F040060
			public const int c83 = 2130968672;
			
			// aapt resource value: 0x7F040061
			public const int c90 = 2130968673;
			
			// aapt resource value: 0x7F040062
			public const int c91 = 2130968674;
			
			// aapt resource value: 0x7F040063
			public const int c92 = 2130968675;
			
			// aapt resource value: 0x7F040064
			public const int c93 = 2130968676;
			
			// aapt resource value: 0x7F040007
			public const int Cabecera = 2130968583;
			
			// aapt resource value: 0x7F040065
			public const int checkConsole = 2130968677;
			
			// aapt resource value: 0x7F040066
			public const int checkProgress = 2130968678;
			
			// aapt resource value: 0x7F040008
			public const int ColumnaAnio = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ColumnaBronce = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ColumnaCiudad = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ColumnaOro = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ColumnaPlata = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int Cuidad1 = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int Cuidad2 = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int Cuidad3 = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int Cuidad4 = 2130968592;
			
			// aapt resource value: 0x7F040067
			public const int dataInputFragment = 2130968679;
			
			// aapt resource value: 0x7F040011
			public const int DebugFragment = 2130968593;
			
			// aapt resource value: 0x7F040068
			public const int eftmessage = 2130968680;
			
			// aapt resource value: 0x7F040012
			public const int Fila1 = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int Fila2 = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int Fila3 = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int Fila4 = 2130968597;
			
			// aapt resource value: 0x7F040069
			public const int g01 = 2130968681;
			
			// aapt resource value: 0x7F04006A
			public const int g02 = 2130968682;
			
			// aapt resource value: 0x7F04006B
			public const int g03 = 2130968683;
			
			// aapt resource value: 0x7F04006C
			public const int g04 = 2130968684;
			
			// aapt resource value: 0x7F04006D
			public const int g05 = 2130968685;
			
			// aapt resource value: 0x7F04006E
			public const int g06 = 2130968686;
			
			// aapt resource value: 0x7F04006F
			public const int g07 = 2130968687;
			
			// aapt resource value: 0x7F040070
			public const int g08 = 2130968688;
			
			// aapt resource value: 0x7F040071
			public const int g09 = 2130968689;
			
			// aapt resource value: 0x7F040072
			public const int g10 = 2130968690;
			
			// aapt resource value: 0x7F040073
			public const int g11 = 2130968691;
			
			// aapt resource value: 0x7F040074
			public const int g12 = 2130968692;
			
			// aapt resource value: 0x7F040075
			public const int headerFragment = 2130968693;
			
			// aapt resource value: 0x7F040016
			public const int InfoFragment = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int LineaCabecera = 2130968599;
			
			// aapt resource value: 0x7F040076
			public const int linearLayout1 = 2130968694;
			
			// aapt resource value: 0x7F040077
			public const int linearLayout2 = 2130968695;
			
			// aapt resource value: 0x7F040078
			public const int linearLayout3 = 2130968696;
			
			// aapt resource value: 0x7F040018
			public const int LineaTotales = 2130968600;
			
			// aapt resource value: 0x7F040079
			public const int linedown = 2130968697;
			
			// aapt resource value: 0x7F04007A
			public const int lineup = 2130968698;
			
			// aapt resource value: 0x7F04007B
			public const int list = 2130968699;
			
			// aapt resource value: 0x7F04007C
			public const int locationInfo = 2130968700;
			
			// aapt resource value: 0x7F04007D
			public const int mainMenu = 2130968701;
			
			// aapt resource value: 0x7F04007E
			public const int message = 2130968702;
			
			// aapt resource value: 0x7F04007F
			public const int mnuclose = 2130968703;
			
			// aapt resource value: 0x7F040080
			public const int mnuloads = 2130968704;
			
			// aapt resource value: 0x7F040081
			public const int mnumain = 2130968705;
			
			// aapt resource value: 0x7F040082
			public const int mnurepair = 2130968706;
			
			// aapt resource value: 0x7F040083
			public const int orderNumber = 2130968707;
			
			// aapt resource value: 0x7F040019
			public const int Oro1 = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int Oro3 = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int Oro4 = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int OroTotal = 2130968604;
			
			// aapt resource value: 0x7F040084
			public const int partnumber = 2130968708;
			
			// aapt resource value: 0x7F04001D
			public const int Plata2 = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int Plata3 = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int Plata4 = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int PlataTotal = 2130968608;
			
			// aapt resource value: 0x7F040085
			public const int qty = 2130968709;
			
			// aapt resource value: 0x7F040086
			public const int readingsInfo = 2130968710;
			
			// aapt resource value: 0x7F040021
			public const int Row0 = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int Row1 = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int Row10 = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int Row11 = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int Row2 = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int Row3 = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int Row4 = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int Row5 = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int Row6 = 2130968617;
			
			// aapt resource value: 0x7F04002A
			public const int Row7 = 2130968618;
			
			// aapt resource value: 0x7F04002B
			public const int Row8 = 2130968619;
			
			// aapt resource value: 0x7F04002C
			public const int Row9 = 2130968620;
			
			// aapt resource value: 0x7F04002D
			public const int RowMessage = 2130968621;
			
			// aapt resource value: 0x7F04002E
			public const int SeparadorCabecera = 2130968622;
			
			// aapt resource value: 0x7F04002F
			public const int SeparadorTotales = 2130968623;
			
			// aapt resource value: 0x7F040087
			public const int seqnr = 2130968711;
			
			// aapt resource value: 0x7F040088
			public const int socksProgress = 2130968712;
			
			// aapt resource value: 0x7F040030
			public const int StatusFragment = 2130968624;
			
			// aapt resource value: 0x7F040089
			public const int t1 = 2130968713;
			
			// aapt resource value: 0x7F04008A
			public const int t2 = 2130968714;
			
			// aapt resource value: 0x7F04008B
			public const int t3 = 2130968715;
			
			// aapt resource value: 0x7F04008C
			public const int t4 = 2130968716;
			
			// aapt resource value: 0x7F04008D
			public const int t5 = 2130968717;
			
			// aapt resource value: 0x7F040031
			public const int Tabla = 2130968625;
			
			// aapt resource value: 0x7F040032
			public const int TextoTotal = 2130968626;
			
			// aapt resource value: 0x7F040033
			public const int Totales = 2130968627;
			
			// aapt resource value: 0x7F04008E
			public const int trolley = 2130968718;
			
			// aapt resource value: 0x7F04008F
			public const int trolleyFragment = 2130968719;
			
			// aapt resource value: 0x7F040090
			public const int vin = 2130968720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050001
			public const int content_main = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int enterDataFt = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int enterOrderFt = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int headerFt = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int infoFt = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int infoSeqFt = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int initialCheckings = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int mainLayout = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int sampleTableLayout = 2131034121;
			
			// aapt resource value: 0x7F050000
			public const int SimpleList = 2131034112;
			
			// aapt resource value: 0x7F05000A
			public const int statusFragment = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int trolleyFt = 2131034123;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int mainMenu = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int menu_main = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Next = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
