//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TESTEntities : DbContext
    {
        public TESTEntities()
            : base("name=TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestTable> TestTable { get; set; }
    
        public virtual int pTestTableAdd(ObjectParameter msg, ObjectParameter idreg, string elCampo1, Nullable<int> elCampo2)
        {
            var elCampo1Parameter = elCampo1 != null ?
                new ObjectParameter("elCampo1", elCampo1) :
                new ObjectParameter("elCampo1", typeof(string));
    
            var elCampo2Parameter = elCampo2.HasValue ?
                new ObjectParameter("elCampo2", elCampo2) :
                new ObjectParameter("elCampo2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pTestTableAdd", msg, idreg, elCampo1Parameter, elCampo2Parameter);
        }
    
        public virtual int pTestTableDel(ObjectParameter msg, Nullable<int> idreg)
        {
            var idregParameter = idreg.HasValue ?
                new ObjectParameter("idreg", idreg) :
                new ObjectParameter("idreg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pTestTableDel", msg, idregParameter);
        }
    
        public virtual int pTestTableUpp(ObjectParameter msg, Nullable<int> idreg, string elCampo1, Nullable<int> elCampo2)
        {
            var idregParameter = idreg.HasValue ?
                new ObjectParameter("idreg", idreg) :
                new ObjectParameter("idreg", typeof(int));
    
            var elCampo1Parameter = elCampo1 != null ?
                new ObjectParameter("elCampo1", elCampo1) :
                new ObjectParameter("elCampo1", typeof(string));
    
            var elCampo2Parameter = elCampo2.HasValue ?
                new ObjectParameter("elCampo2", elCampo2) :
                new ObjectParameter("elCampo2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pTestTableUpp", msg, idregParameter, elCampo1Parameter, elCampo2Parameter);
        }
    }
}
